apiVersion: v1
kind: Template
metadata:
  name: aprodcazamasivos
  annotations:
    description: "Template para generacion del servicio de aprodcazamasivos para Telefonica"
    iconClass: "icon-rh-integration"
objects:
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: aprodcazamasivos
        app.kubernetes.io/component: aprodcazamasivos
        app.kubernetes.io/instance: aprodcazamasivos
      name: aprodcazamasivos
      namespace: cazamasivos
    spec:
      replicas: 1
      revisionHistoryLimit: 10
      selector:
        app: aprodcazamasivos
        deploymentconfig: aprodcazamasivos
      strategy:
        activeDeadlineSeconds: 21600
        resources: { }
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          annotations:
            openshift.io/generated-by: OpenShiftNewApp
            sidecar.istio.io/inject: "true"
          labels:
            app: aprodcazamasivos
            deploymentconfig: aprodcazamasivos
        spec:
          containers:
            - name: aprodcazamasivos
              env:
                - name: TZ
                  value: UTC+5
              image: 'aproddevopsrc.azurecr.io/aprodcazamasivos:1.0'
              imagePullPolicy: Always
              resources:
                limits:
                  cpu: 400m
                  memory: 1Gi
                requests:
                  cpu: 200m
                  memory: 640Mi
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: { }
          terminationGracePeriodSeconds: 30
          runAsNonRoot: false
          hostAliases:
            - ip: 10.86.6.26
              hostnames:
                - aprodcazamasivosdb.documents.azure.com       
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: aprodcazamasivos
        app.kubernetes.io/component: aprodcazamasivos
        app.kubernetes.io/instance: aprodcazamasivos
      name: aprodcazamasivos
      namespace: cazamasivos
    spec:
      ports:
        - port: 1887
          protocol: UDP