kind: Deployment
apiVersion: apps/v1
metadata:
  name: aprodcazamasivos
  namespace: cazamasivos
  labels:
    app: aprodcazamasivos
    app.kubernetes.io/component: aprodcazamasivos
    app.kubernetes.io/instance: aprodcazamasivos
    app.kubernetes.io/part-of: aprodcazamasivos-app
    app.openshift.io/runtime-namespace: cazamasivos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aprodcazamasivos
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: aprodcazamasivos
        deploymentconfig: aprodcazamasivos
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
    spec:
      containers:
        - resources:
            limits:
              memory: 4Gi
            requests:
              cpu: 40m
              memory: 51m
          terminationMessagePath: /dev/termination-log
          name: aprodcazamasivos
          ports:
            - containerPort: 1887
              protocol: UDP
          imagePullPolicy: Always
          terminationMessagePolicy: File
          image: 'aproddevopsrc.azurecr.io/aprodcazamasivos:1.0'
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext:
        runAsNonRoot: false
      schedulerName: default-scheduler
      hostAliases:
        - ip: 10.86.6.26
          hostnames:
            - aprodcazamasivosdb.documents.azure.com
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600